### ISSUE TITLE
Android 启动页出现java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by goodxianping** [alipay/mpaas-demo#23]
2019-09-11 12:48:49.313 5935-6095/com.mpaas.demo E/automationcrash: Force End parse for automation
2019-09-11 12:48:49.314 5935-6095/com.mpaas.demo E/LauncherApplication: [ORDERED_2] java.lang.UnsatisfiedLinkError: No implementation found for int com.alibaba.sqlcrypto.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_com_alibaba_sqlcrypto_sqlite_SQLiteConnection_nativeOpen and Java_com_alibaba_sqlcrypto_sqlite_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ)
        at com.alibaba.sqlcrypto.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at com.alibaba.sqlcrypto.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
        at com.alibaba.sqlcrypto.sqlite.SQLiteConnection.open(SQLiteConnection.java:233)
        at com.alibaba.sqlcrypto.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:467)
        at com.alibaba.sqlcrypto.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:188)
        at com.alibaba.sqlcrypto.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:180)
        at com.alibaba.sqlcrypto.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:841)
        at com.alibaba.sqlcrypto.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:826)
        at com.alibaba.sqlcrypto.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:718)
        at com.alibaba.sqlcrypto.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:752)
        at com.alibaba.sqlcrypto.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:237)
        at com.alibaba.sqlcrypto.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:168)
        at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:72)
        at com.j256.ormlite.android.AndroidConnectionSource.getReadOnlyConnection(AndroidConnectionSource.java:60)
        at com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:250)
        at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:204)
        at com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:278)
        at com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:368)
        at com.mpaas.cdp.biz.dao.impl.AdDaoImpl.getSpaceInfoList(AdDaoImpl.java:110)
        at com.mpaas.cdp.biz.db.AdDBCacheSingleton.checkSpaceData(AdDBCacheSingleton.java:85)
        at com.mpaas.cdp.biz.db.AdDBCacheSingleton.isDBEmpty(AdDBCacheSingleton.java:511)
        at com.mpaas.cdp.biz.transport.AdExecutorService$2.run(AdExecutorService.java:171)
        at com.alipay.mobile.framework.pipeline.analysis.AnalysedRunnable.run(AnalysedRunnable.java:86)
        at com.alipay.mobile.framework.pipeline.DelayedRunnable.run(DelayedRunnable.java:65)
        at com.alipay.mobile.framework.service.common.threadpool.TaskPoolRunnable.run(TaskPoolRunnable.java:128)
        at com.alipay.mobile.framework.service.common.OrderedExecutor$Task.run(OrderedExecutor.java:192)
        at com.alipay.mobile.framework.pipeline.analysis.AnalysedRunnable.run(AnalysedRunnable.java:82)
        at com.alipay.mobile.framework.pipeline.DelayedRunnable.run(DelayedRunnable.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2019-09-11 12:48:49.315 5935-6074/com.mpaas.demo I/LogContext: [PIPELINE.INITED] uploadCoreByStartService: start upload service, logCategory: footprint, success: true, process: main, disableTools: false, event: 
2019-09-11 12:48:49.315 5935-6074/com.mpaas.demo W/LauncherApplication: [PIPELINE.INITED] upload(upload=footprint)

**Comment by goodxianping** [comment]
--------- beginning of crash
2019-09-11 12:48:49.540 5935-5935/com.mpaas.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mpaas.demo, PID: 5935
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mpaas.demo/com.mpaas.demo.launcher.MainActivity}: android.content.res.Resources$NotFoundException: resourceId=[0x24020000][604110848], packageId=[36], mPackageIDs=[size=1: 127], bundle=Bundle: VERSION=5,name=application_resources,version=3.0.0.0,location=/data/app/com.mpaas.demo-2/base.apk, size=-1, md5=null, mDescription={_depends.size=110, bad cookies:[size=38: 27->extractBundle->0,28->extractBundle->0,29->extractBundle->0,30->extractBundle->0,34->extractBundle->0,36->extractBundle->0,37->extractBundle->0,38->extractBundle->0,41->extractBundle->0,42->extractBundle->0,44->extractBundle->0,45->extractBundle->0,47->extractBundle->0,48->extractBundle->0,49->extractBundle->0,50->extractBundle->0,51->extractBundle->0,52->extractBundle->0,53->extractBundle->0,54->extractBundle->0,55->extractBundle->0,56->extractBundle->0,57->extractBundle->0,58->extractBundle->0,60->extractBundle->0,69->extractBundle->0,72->extractBundle->0,75->extractBundle->0,76->extractBundle->0,77->extractBundle->0,80->extractBundle->0,81->extractBundle->0,82->extractBundle->0,98->extractBundle->0,100->extractBundle->0,103->extractBundle->0,110->extractBundle->0,325->extractBundle->0], appAvailableSpace:606.96094MB, totalSpace:774.8906MB}, assignedPackageIDs=[size=4: 1,2,31,127], assetsManager=android.content.res.AssetManager@bde7edd, useOriginAssets=false, stringBlocks=3 >>> are you using correct Context?
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: android.content.res.Resources$NotFoundException: resourceId=[0x24020000][604110848], packageId=[36], mPackageIDs=[size=1: 127], bundle=Bundle: VERSION=5,name=application_resources,version=3.0.0.0,location=/data/app/com.mpaas.demo-2/base.apk, size=-1, md5=null, mDescription={_depends.size=110, bad cookies:[size=38: 27->extractBundle->0,28->extractBundle->0,29->extractBundle->0,30->extractBundle->0,34->extractBundle->0,36->extractBundle->0,37->extractBundle->0,38->extractBundle->0,41->extractBundle->0,42->extractBundle->0,44->extractBundle->0,45->extractBundle->0,47->extractBundle->0,48->extractBundle->0,49->extractBundle->0,50->extractBundle->0,51->extractBundle->0,52->extractBundle->0,53->extractBundle->0,54->extractBundle->0,55->extractBundle->0,56->extractBundle->0,57->extractBundle->0,58->extractBundle->0,60->extractBundle->0,69->extractBundle->0,72->extractBundle->0,75->extractBundle->0,76->extractBundle->0,77->extractBundle->0,80->extractBundle->0,81->extractBundle->0,82->extractBundle->0,98->extractBundle->0,100->extractBundle->0,103->extractBundle->0,110->extractBundle->0,325->extractBundle->0], appAvailableSpace:606.96094MB, totalSpace:774.8906MB}, assignedPackageIDs=[size=4: 1,2,31,127], assetsManager=android.content.res.AssetManager@bde7edd, useOriginAssets=false, stringBlocks=3 >>> are you using correct Context?
        at com.alipay.mobile.quinox.resources.a.a(BundleResources.java:750)
        at com.alipay.mobile.quinox.resources.a.getLayout(BundleResources.java:186)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:414)
        at android.app.Activity.setContentView(Activity.java:2414)
2019-09-11 12:48:49.541 5935-5935/com.mpaas.demo E/AndroidRuntime:     at com.alipay.mobile.framework.app.ui.BaseFragmentActivity.setContentView(BaseFragmentActivity.java:609)
        at com.mpaas.demo.launcher.MainActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at com.alipay.mobile.quinox.activity.QuinoxInstrumentation.callActivityOnCreate(QuinoxInstrumentation.java:555)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        	... 9 more
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x24020000
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2094)
        at android.content.res.Resources.getLayout(Resources.java:1111)
        at com.alipay.mobile.quinox.resources.a.getLayout(BundleResources.java:184)
        	... 19 more

**Comment by SpinyTech** [comment]
您这个是 bundle portal 形式吗？目前这个 github 下面暂时只处理 mpaas inside 模式的问题。

**Comment by goodxianping** [comment]
> 您这个是 bundle portal 形式吗？目前这个 github 下面暂时只处理 mpaas inside 模式的问题。

官网的mPaasDemo问题找谁处理？

**Comment by glcrazier** [comment]
@goodxianping 特定机型上的崩溃，还是多个机型？

**Comment by SpinyTech** [comment]
> > 您这个是 bundle portal 形式吗？目前这个 github 下面暂时只处理 mpaas inside 模式的问题。
> 
> 官网的mPaasDemo问题找谁处理？

可以在金融云或阿里云提工单进行处理

**Comment by brainweiyi** [comment]
解决了吗
