### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;

### ISSUE THREAD

**Issue by goodxianping** [alipay/mpaas-demo#26]
2019-09-16 15:47:47.401 13265-13265/com.trxnet.dragongo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trxnet.dragongo, PID: 13265
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
        at com.alipay.mobile.antui.basic.AUBasicDialog.onWindowFocusChanged(AUBasicDialog.java:37)
        at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1692)
        at android.view.View.dispatchWindowFocusChanged(View.java:13703)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1480)
        at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2870)
        at android.view.ViewRootImpl.access$1100(ViewRootImpl.java:142)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4533)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.trxnet.dragongo-q06ooJ4BY-3MJJh961UVoA==/base.apk"],nativeLibraryDirectories=[/data/app/com.trxnet.dragongo-q06ooJ4BY-3MJJh961UVoA==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.alipay.mobile.antui.basic.AUBasicDialog.onWindowFocusChanged(AUBasicDialog.java:37) 
        at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1692) 
        at android.view.View.dispatchWindowFocusChanged(View.java:13703) 
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1480) 
        at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2870) 
        at android.view.ViewRootImpl.access$1100(ViewRootImpl.java:142) 
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4533) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2019-09-16 15:47:47.427 13265-13265/com.trxnet.dragongo I/Process: Sending signal. PID: 13265 SIG: 9

**Comment by glcrazier** [comment]
没引入support v4吧
