### ISSUE TITLE
离线包更新失败

### ISSUE THREAD

**Issue by 947635060** [alipay/mpaas-demo#3]
按照文档和视频的都试过，执行下面方法
MPNebula.updateAllApp(new MpaasNebulaUpdateCallback() {
                    @Override
                    public void onResult(final boolean success, final boolean isLimit) {
                        // success 为是否成功
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(MainActivity.this, success ? "离线包更新成功" : "离线包更新失败", Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                });

success 一直为false，看文档很多次都没看到有什么问题。有谁知道到底缺少了什么步骤？

**Comment by 947635060** [comment]
离线资源都是按照文档的一样，还有离线资源是文档提供的

**Comment by SpinyTech** [comment]
您的包名有换吗，直接编译 demo 可以更新么，过滤下 getUnionResource 贴下日志。

**Comment by SpinyTech** [comment]
长时间未回复，close

**Comment by IvanCai** [comment]
我也遇到了同样的问题，以下是错误的日志。
`01-20 11:35:20.079 11581-11723/dankal.cn.ali_mpass_demo I/mynet_RpcInvoker: [URGENT_DISP_1] ThreadId=[1594]  invoke. object=[com.alipay.mobileappcommon.biz.rpc.dynamic.UnionResourceFacade]  methodName=[getUnionResource]
01-20 11:35:20.103 11581-11723/dankal.cn.ali_mpass_demo D/mynet_RpcInvoker: [URGENT_DISP_1] [getSignData] sign content: Operation-Type=alipay.client.getUnionResource&Request-Data=CAASIE9ORVgyOEI1N0JGMTYxNjEwX0FORFJPSUQtZGFua2FsGgMxLjAiAzEuMCoYV0RiSXRPK0ZFRUVEQUpvN0JLZGZTRnAyMh8yMDAxMTcxNzE0NDg5MTN8ODYxMzM3MDMxMzI4ODIwOgMzNjBCCDE1MDUtQTAxSAFSDW1wYWFzX2RlZmF1bHRaAjIzYgM2LjBqDURhbmthbC1Nb2JpbGVyAnt9ehUIBDIRCgVhcHBpZBIIMjAyMDAxMTaCAQZ1c2VySWSKAR1hcm02NC12OGEsYXJtZWFiaS12N2EsYXJtZWFiaZIBAzM2MA==&Ts=M/11E4c
01-20 11:35:20.374 11581-11723/dankal.cn.ali_mpass_demo E/SecurityManager: [URGENT_DISP_1] [signature] Exception: com.alibaba.wireless.security.open.SecException:  ErrorCode = 608
    com.alibaba.wireless.security.open.SecException: 
        at com.taobao.wireless.security.adapter.JNICLibrary.doCommandNative(Native Method)
        at com.alibaba.wireless.security.mainplugin.a.doCommand(Unknown Source)
        at com.taobao.wireless.security.adapter.a.b.a(Unknown Source)
        at com.taobao.wireless.security.adapter.a.b.a(Unknown Source)
        at com.taobao.wireless.security.adapter.a.b.a(Unknown Source)
        at com.alibaba.wireless.security.open.securesignature.a.signRequest(Unknown Source)
        at com.alipay.mobile.common.netsdkextdepend.security.DefaultSecurityManager.a(DefaultSecurityManager.java:130)
        at com.alipay.mobile.common.netsdkextdepend.security.DefaultSecurityManager.signature(DefaultSecurityManager.java:36)
        at com.alipay.mobile.common.netsdkextdependapi.security.SecurityUtil.signature(SecurityUtil.java:15)
        at com.alipay.mobile.common.transport.utils.RpcSignUtil.signature(RpcSignUtil.java:47)
        at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:469)
        at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:681)
        at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:524)
        at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:442)
        at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:145)
        at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:67)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy3.getUnionResource(Unknown Source)
        at com.alipay.android.phone.mobilecommon.dynamicrelease.nebula.NebulaCenterOperator.rpcRequest(NebulaCenterOperator.java:167)
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.rpcCall(MPAppBizRpcImpl.java:119)
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.app(MPAppBizRpcImpl.java:50)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.request(H5BaseAppProvider.java:650)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.updateAppWithReqFinally(H5BaseAppProvider.java:584)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.access$000(H5BaseAppProvider.java:55)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider$1.run(H5BaseAppProvider.java:150)
        at com.alipay.mobile.framework.pipeline.analysis.AnalysedRunnable.run(AnalysedRunnable.java:86)
        at com.alipay.mobile.framework.pipeline.DelayedRunnable.run(DelayedRunnable.java:65)
        at com.alipay.mobile.framework.service.common.threadpool.TaskPoolRunnable.run(TaskPoolRunnable.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
01-20 11:35:20.381 11581-11723/dankal.cn.ali_mpass_demo I/mynet_HttpCaller: [URGENT_DISP_1] threadid = 1594; Request info: Url : https://cn-hangzhou-component-gw.cloud.alipay.com/mgw.htm,HttpHeader: [WorkspaceId: dankal, AppId: ONEX28B57BF161610, Platform: ANDROID, productVersion: 1.8.5.191206152900, productId: ONEX28B57BF161610_ANDROID, Version: 2, Did: WDbItO+FEEEDAJo7BKdfSFp2, Operation-Type: alipay.client.getUnionResource, Ts: M/11E4c, Content-Type: application/protobuf], Tags: {UUID=WDbItO+FEEEDAJo7BKdfSFp2M/11E4c, sign_error_code=608, reqDataDigest=cL1f8FmJEF409cf212TP5g==
    , id=1, sign_time=270, rpcVersion=2, operationType=alipay.client.getUnionResource}, Body�� ONEX28B57BF161610_ANDROID-dankal1.0"1.0*WDbItO+FEEEDAJo7BKdfSFp22200117171448913|861337031328820:3601505-A01HRmpaas_defaultZ23b6.0jDankal-Mobiler{}z2
    appid20200116�userId�arm64-v8a,armeabi-v7a,armeabi�360
01-20 11:35:20.385 11581-11723/dankal.cn.ali_mpass_demo D/mynet_BgRpc: [URGENT_DISP_1] Background RPC： alipay.client.getUnionResource
01-20 11:35:20.389 11581-11757/dankal.cn.ali_mpass_demo D/mynet_ActThreadPoolExecutor: [HttpManager.HttpWorker#bg#1] beforeExecute: TASK_TYPE_BG_RPC,alipay.client.getUnionResource
01-20 11:35:20.413 11581-11757/dankal.cn.ali_mpass_demo I/mynet_HttpWorker: [HttpManager.HttpWorker#bg#1] printHeaderLog.  : WorkspaceId:dankal, AppId:ONEX28B57BF161610, Platform:ANDROID, productVersion:1.8.5.191206152900, productId:ONEX28B57BF161610_ANDROID, Version:2, Did:WDbItO+FEEEDAJo7BKdfSFp2, Operation-Type:alipay.client.getUnionResource, Ts:M/11E4c, Content-Type:application/protobuf, Cookie:, Accept-Language:zh-Hans, Accept-Encoding:gzip, Connection:Keep-Alive, Retryable2:0, 
01-20 11:35:20.417 11581-11757/dankal.cn.ali_mpass_demo D/mynet_HttpWorker: [HttpManager.HttpWorker#bg#1] By Http/Https to request. operationType=alipay.client.getUnionResource  method=POST url=https://cn-hangzhou-component-gw.cloud.alipay.com/mgw.htm allowRetry=false
01-20 11:35:20.423 11581-11757/dankal.cn.ali_mpass_demo I/System.out: test:Operation-Type:alipay.client.getUnionResource
01-20 11:35:20.776 11581-11757/dankal.cn.ali_mpass_demo D/mynet_HttpWorker: [HttpManager.HttpWorker#bg#1] operationType=alipay.client.getUnionResource ,url=https://cn-hangzhou-component-gw.cloud.alipay.com/mgw.htm ,readed data length: 0,header content-length: 0
01-20 11:35:20.778 11581-11757/dankal.cn.ali_mpass_demo I/mynet_HttpWorker: [HttpManager.HttpWorker#bg#1] threadid = 1609; Response success. mOperationType=[alipay.client.getUnionResource] . response header=[HttpUrlHeader{headers=Date:Mon, 20 Jan 2020 03:35:24 GMT,Content-Length:0,Connection:keep-alive,Strict-Transport-Security:max-age=31536000,Result-memo:%E9%AA%8C%E7%AD%BE%E7%9A%84%E5%8F%82%E6%95%B0%E4%B8%8D%E5%A4%9F%E3%80%82,Result-Status:7001,Result-tips:%E7%AD%BE%E5%90%8D%E9%AA%8C%E8%AF%81%E5%A4%B1%E8%B4%A5%E3%80%82,}].  response body =   
01-20 11:35:20.789 11581-11723/dankal.cn.ali_mpass_demo D/mynet_RpcInvoker: [URGENT_DISP_1] RPC,RPC_ERROR,DEBUG,-,ERR_MSG=com.alipay.mobile.common.rpc.RpcException: RPCException: [7001] : ^API=alipay.client.getUnionResource^ERR_CODE=7001^
01-20 11:35:20.791 11581-11723/dankal.cn.ali_mpass_demo D/mynet_RpcInvoker: [URGENT_DISP_1] ThreadId=[1594] methodName=[getUnionResource] API=[alipay.client.getUnionResource] invokeTiming=[710]
01-20 11:35:20.792 11581-11723/dankal.cn.ali_mpass_demo E/DynamicRelease: [URGENT_DISP_1] com.alipay.mobile.common.rpc.RpcException: RPCException: [7001] : 
        at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.preProcessResponse(RpcInvokerUtil.java:90)
        at com.alipay.mobile.common.rpc.protocol.protobuf.PBDeserializer.parser(PBDeserializer.java:36)
        at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:221)
        at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:146)
        at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:67)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy3.getUnionResource(Unknown Source)
        at com.alipay.android.phone.mobilecommon.dynamicrelease.nebula.NebulaCenterOperator.rpcRequest(NebulaCenterOperator.java:167)
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.rpcCall(MPAppBizRpcImpl.java:119)
        at com.mpaas.nebula.adapter.api.MPAppBizRpcImpl.app(MPAppBizRpcImpl.java:50)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.request(H5BaseAppProvider.java:650)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.updateAppWithReqFinally(H5BaseAppProvider.java:584)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider.access$000(H5BaseAppProvider.java:55)
        at com.alipay.mobile.nebula.baseprovider.H5BaseAppProvider$1.run(H5BaseAppProvider.java:150)
        at com.alipay.mobile.framework.pipeline.analysis.AnalysedRunnable.run(AnalysedRunnable.java:86)
        at com.alipay.mobile.framework.pipeline.DelayedRunnable.run(DelayedRunnable.java:65)
        at com.alipay.mobile.framework.service.common.threadpool.TaskPoolRunnable.run(TaskPoolRunnable.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
01-20 11:35:20.797 11581-11738/dankal.cn.ali_mpass_demo I/TrafficPowerHandler: [LowPriNetworkThread#1] noteTraficConsume, 0, 0, 0, WIFI, https://cn-hangzhou-component-gw.cloud.alipay.com/mgw.htm#alipay.client.getUnionResource, cn-hangzhou-component-gw.cloud.alipay.com, 233, 0, null, HC_RPC, null, currentPage: null, currentUrl: null, HTTPCLIENT_RPC, bundle=null, appId=null, diagnose=alipay.client.getUnionResource, isUpload=false, fileId=null, bizId=null, tmp_cost_time=43576834, null, currentPage=null, currentUrl=null
01-20 11:35:20.807 11581-11780/dankal.cn.ali_mpass_demo D/mynet_RPC_PERF: [LowPriNetworkThread#1] RPC_PERF:RPC,RPC,INFO,https,TTS=0.387^TCP_TIME=44ms^SIGN_ERROR_CODE=608^TMRX=0^READ_TIME=1ms^SSL_TIME=164ms^RES_SIZE=0^TAG=def^SIGN_TIME=270ms^REQ_RAW_SIZE=235^SPEED=0.2689^hlas=T^OLD_RPC_ALL_TIME=366ms^GW_RS=7001^STALLED_TIME=8ms^DT=iprank^QOS=2_2044.0000^TARGET_HOST=116.62.85.233:443^RESULT=T^BWW=0.2689^BW=0.0050^TTX=3616^RPC_ALL_TIME=395ms^GROUND=FG^TRX=10026^EXT1=F^TMTX=0^UUID=WDbItO+FEEEDAJo7BKdfSFp2M/11E4c^PRIO=BG^HRC=200^ALL_TIME=358ms^REQ_SIZE=233^NETTYPE=0_0^DNS_TIME=84ms^API=alipay.client.getUnionResource^
`
